spring.application.name=Warehouse Dispatcher

spring.jpa.defer-datasource-initialization=true
timefold.solver.termination.spent-limit=10s
spring.devtools.restart.enabled=false
spring.jpa.hibernate.ddl-auto=update
